apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-hub-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-hub-api
  template:
    metadata:
      labels:
        app: devops-hub-api
    spec:
      containers:
      - name: api
        image: devops-hub-api:latest
        ports:
        - containerPort: 8080 